version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "REACT_APP_EXPERIMENTER_API_ROOT_URL=https://localhost/api REACT_APP_NORMANDY_ADMIN_API_ROOT_URL=https://localhost:8000/api/ yarn start"
    ports:
      - "3000:3000"
volumes:
  node_modules_volume:

networks:
  private_nw:
    internal: true